### ISSUE TITLE
add conditionals to fine-tune job execution

### ISSUE THREAD

**Issue by mbruns91** [pyiron/actions#54]
When going through our repos, I realized that not all do actually contain a documentation (e.g. [structuretoolkit](https://github.com/pyiron/structuretoolkit)) in the form of a `doc/` directory, containig files `conf.py` and `index.rst` as it is expected by e.g. [`push-pull-main.yml`](https://github.com/pyiron/actions/blob/main/.github/workflows/push-pull-main.yml).
Also, in `structuretoolkit`, there is a `mini` workflow, which only runs unit-, benchmark- and integration-test on a minimal environment, I mentioned this also [here](https://github.com/pyiron/structuretoolkit/issues/96), so only a subset of the stuff [`push-pull-main.yml`](https://github.com/pyiron/actions/blob/main/.github/workflows/push-pull-main.yml) is doing. I changed the workflow there, to use our centralized actions, which was mainly copy-pasting from `push-pull-main.yml`.

What do you think about adding non-required conditionals to our workflows? We could set a variable like `run_build-doc`, which defaults to `run_build-doc: 'true'` and add a [boolean eval](https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution) before each segment, e.g.
```yml
if: run_build-docs == 'true'
  build-docs:
      needs: commit-updated-env
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: pyiron/actions/build-docs@main
          with:
            python-version: '3.11'
            env-prefix: /usr/share/miniconda3/envs/my-env
            env-label: linux-64-py-3-11
            env-files: ${{ inputs.docs-env-files }}
```
However, I haven't yet found anything explaining me, how to actually use a variable of type bool or so, so this can only be done via strings `'true'` and `'false'`.
In the calling workflow, one could then control which parts of the 'central workflow' are executed. I hope, this further reduces the need to have really customized workflows in repositories to do stuff as described above.
